# Generated by Django 4.0.6 on 2022-07-18 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='retal_price_day',
            new_name='rental_price_day',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='retal_peroid',
            new_name='rental_time',
        ),
    ]
